<?php if (!empty($this->msgid)) {?>
<div class='msg_ok'><?php echo $this->translate('Bedankt voor je deelname!');?></div>
<br/>
<?php }?>
<?php 
$ii=0;
if (!empty($this->result)){
?>
<div class="hoofding" style="margin-top:5px;"><?php echo $this->translate('Algemene rangschikking');?></div>
<br/>

<div style="float:left;">
<img src="/wkprono/public/images/skilzy2.jpg" alt="Logo" width="300">
</div>
<div style="float:left;">
<table  class="gridtable" style="width:99%;margin-left:5%;font-size:16px;white-space: nowrap;">
	<thead>
	<tr>
		<th><?php echo $this->translate('Nr'); ?></th>
		<th><?php echo $this->translate('Naam'); ?></th>               
		<th style="text-align:right;"><?php echo $this->translate('Punten'); ?>&nbsp;&nbsp;</th>
	</tr>
	</thead>
	<tbody>
        <?php foreach ($this->result as $r) { ?>
        <?php $ii++;?>
	<tr>
		<td align='center'>
                    <?php echo $r['betaald']?$ii:"<font color='red'>".$ii."</font>"; ?>   
		</td>
		<td style="width:350px;">
		<?php if ($this->view) {?>
					<a href="<?php echo $this->baseUrl();?>/index/detail/id/<?php echo $r['id']; ?>"><?php echo $r['naam']; ?></a>
                                        <?php echo ($ii==1)?"<img src='/wkprono/public/images/Sports-World-Cup-icon1.png'>":"";?> 
                                        <?php echo ($ii==2)?"<img src='/wkprono/public/images/Sports-World-Cup-icon2.png'>":"";?> 
                                        <?php echo ($ii==3)?"<img src='/wkprono/public/images/Sports-World-Cup-icon3.png'>":"";?> 
		<?php } else {?>        
                    <?php echo $r['betaald']?$r['naam']:"<font color='red'>".$r['naam']."</font>"; ?>   
		<?php }?>
		</td>
        <td style="text-align:right;"><?php echo $r['score']; ?>&nbsp;&nbsp;</td>
	</tr>
	
        <?php } ?>
	</tbody>	
</table>
</div>
<?php 
}
